/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package food.ordering.system;

import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ganashree
 */
public class customer_address extends javax.swing.JFrame {

    /**
     * Creates new form customer_address
     */
    public customer_address() {
        initComponents();
        Connect();
        this.setLocationRelativeTo(null);
        
    }
   
     Connection con;
    PreparedStatement pst;
    ResultSet rs;





 public void Connect()
{
try {
Class.forName("com.mysql.cj.jdbc.Driver");
con = DriverManager.getConnection("jdbc:mysql://localhost/main_menu","root","");


} catch (ClassNotFoundException | SQLException ex) {
Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
}
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        streets = new javax.swing.JTextField();
        citys = new javax.swing.JTextField();
        districts = new javax.swing.JTextField();
        pincodes = new javax.swing.JTextField();
        phnos = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        adresssubmbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(java.awt.Color.white);
        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(" CUSTOMER   Address");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, 459, 72));

        streets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streetsActionPerformed(evt);
            }
        });
        getContentPane().add(streets, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 138, 217, 36));

        citys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                citysActionPerformed(evt);
            }
        });
        getContentPane().add(citys, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 197, 217, 36));

        districts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                districtsActionPerformed(evt);
            }
        });
        getContentPane().add(districts, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 251, 217, 36));

        pincodes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pincodesActionPerformed(evt);
            }
        });
        getContentPane().add(pincodes, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 217, 36));

        phnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phnosActionPerformed(evt);
            }
        });
        getContentPane().add(phnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 373, 217, 36));

        jLabel7.setBackground(java.awt.Color.white);
        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 1, 32)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Street :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 133, 119, -1));

        jLabel8.setBackground(java.awt.Color.white);
        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 1, 32)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("City :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 192, 166, -1));

        jLabel9.setBackground(java.awt.Color.white);
        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 1, 32)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("District :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 246, 166, -1));

        jLabel10.setBackground(java.awt.Color.white);
        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 1, 32)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Pincode :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 305, 166, -1));

        jLabel11.setBackground(java.awt.Color.white);
        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 1, 32)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Phno  :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 373, 131, -1));

        adresssubmbtn.setBackground(java.awt.Color.white);
        adresssubmbtn.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        adresssubmbtn.setText("SUBMIT");
        adresssubmbtn.setBorder(new javax.swing.border.MatteBorder(null));
        adresssubmbtn.setInheritsPopupMenu(true);
        adresssubmbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adresssubmbtnActionPerformed(evt);
            }
        });
        getContentPane().add(adresssubmbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 444, 174, 62));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/food/ordering/system/pic5.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void streetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streetsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_streetsActionPerformed

    private void citysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_citysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_citysActionPerformed

    private void districtsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_districtsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_districtsActionPerformed

    private void pincodesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pincodesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pincodesActionPerformed

    private void phnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phnosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phnosActionPerformed

    private void adresssubmbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adresssubmbtnActionPerformed
   

        
      
        
        String street = streets.getText();
       String city = citys.getText();
       String district = districts.getText();
       String pincode = pincodes.getText();
        String phno = phnos.getText();

       
       
       
   try{
        pst = con.prepareStatement("INSERT into address(street,city,district,pincode,phno)values(?,?,?,?,?) ");
        pst.setString(1,street);
        pst.setString(2,city);
        pst.setString(3,district);
        pst.setString(4,pincode);
        pst.setString(5,phno);



       
       
           streets.setText("");
           citys.setText("");
           districts.setText("");
                      citys.setText("");
                               phnos.setText("");


           
//           streets.requestFocus();
//                      districts.requestFocus();
//           citys.requestFocus();
//           phnos.requestFocus();

           int k = pst.executeUpdate();
           
       if(k==1){
        JOptionPane.showMessageDialog(this, "Registered");
        this.dispose();
       
       }
   
         
       
       }catch (SQLException ex) {
           
      System.err.println("Message: " + ex.getMessage());

        }
        
         new reviews().setVisible(true);
                  

    
    }//GEN-LAST:event_adresssubmbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customer_address.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customer_address.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customer_address.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customer_address.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customer_address().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adresssubmbtn;
    private javax.swing.JTextField citys;
    private javax.swing.JTextField districts;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField phnos;
    private javax.swing.JTextField pincodes;
    private javax.swing.JTextField streets;
    // End of variables declaration//GEN-END:variables
}
