/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package food.ordering.system;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ganashree
 */
public class customer_location_details extends javax.swing.JFrame {

    /**
     * Creates new form customer_location_details
     */
    public customer_location_details() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        custsubmit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_custo = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(java.awt.Color.black);
        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 60)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("CUSTOMER DATA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        custsubmit.setBackground(java.awt.Color.white);
        custsubmit.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        custsubmit.setText("GET DATA");
        custsubmit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        custsubmit.setInheritsPopupMenu(true);
        custsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custsubmitActionPerformed(evt);
            }
        });
        getContentPane().add(custsubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, 330, 62));

        table_custo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "uid", "street", "city", "district", "pincode", "phno"
            }
        ));
        table_custo.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(table_custo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 124, 609, 343));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/food/ordering/system/piii.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void custsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custsubmitActionPerformed
 try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/main_menu","root","");

            PreparedStatement pst = con.prepareStatement("select * from address");
            ResultSet rs = pst.executeQuery();

            while(rs.next()){
                String uid = String.valueOf(rs.getInt("uid"));
                String street = rs.getString("street");
                String city = rs.getString("city");
                String district = rs.getString("pincode");
                                String pincode = rs.getString("district");
                                                String phno = rs.getString("phno");


//                String pincode =String.valueOf(rs.getInt("pincode"));
//                String phno = String.valueOf(rs.getLong("phno"));
               

                String tbdata[] = {uid,street,city,district,pincode,phno};
                DefaultTableModel tblModel = (DefaultTableModel)table_custo.getModel();
                tblModel.addRow(tbdata);

            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(data.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }//GEN-LAST:event_custsubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customer_location_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customer_location_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customer_location_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customer_location_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customer_location_details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton custsubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_custo;
    // End of variables declaration//GEN-END:variables
}
