/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package food.ordering.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ganashree
 */
public class reviews extends javax.swing.JFrame {

    /**
     * Creates new form customer_address
     */
    public reviews() {
        initComponents();
        Connect();
    }
     Connection con1;
     Connection con;
    PreparedStatement pst;
    ResultSet rs;





 public void Connect()
{
try {
Class.forName("com.mysql.cj.jdbc.Driver");
con = DriverManager.getConnection("jdbc:mysql://localhost/main_menu","root","");


} catch (ClassNotFoundException | SQLException ex) {
Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
}
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        revbtn = new javax.swing.JButton();
        revi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(java.awt.Color.white);
        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("R E V I E W S");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 0, 280, 72));

        jLabel7.setBackground(java.awt.Color.white);
        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 1, 32)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 204));
        jLabel7.setText("please give rating from 1 to 5");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 156, 410, 38));

        revbtn.setBackground(java.awt.Color.white);
        revbtn.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        revbtn.setText("SUBMIT");
        revbtn.setBorder(new javax.swing.border.MatteBorder(null));
        revbtn.setInheritsPopupMenu(true);
        revbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revbtnActionPerformed(evt);
            }
        });
        getContentPane().add(revbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 216, 174, 62));
        getContentPane().add(revi, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 100, 202, 38));

        jLabel8.setBackground(java.awt.Color.white);
        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 1, 32)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Stars   :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 79, 119, 59));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/food/ordering/system/pic3.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void revbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revbtnActionPerformed

              
       String rev = revi.getText();
    
       
       
       
   try{
        pst = con.prepareStatement("insert into rating(rev_stars)values(?)");
               pst.setString(1,rev);

    
            revi.setText("");
        
           revi.requestFocus();

           int k = pst.executeUpdate();
           
       if(k==1){
        JOptionPane.showMessageDialog(this, "Thank you for Rating");
        this.dispose();
       
       }
  
       
       }catch (SQLException ex) {
           
      System.err.println("Message: " + ex.getMessage());

        }
              
              

          
  
         
        
      
       
       
       
   
    
    }//GEN-LAST:event_revbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reviews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reviews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reviews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reviews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reviews().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton revbtn;
    private javax.swing.JTextField revi;
    // End of variables declaration//GEN-END:variables
}
